services:
  restmon:
    image: restmon:latest
    build: ..
    container_name: restmon_test
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/platform"]
      interval: 2s
      timeout: 2s
      retries: 10